name: 'Summarise dbt-contracts results'
description: 'Creates a summary table on actions to summarise results from dbt-contracts'
author: 'George Martin Marino'
branding:
  icon: 'table'
  color: 'purple'
inputs:
  title:
    description: 'Title of the summary'
    required: false
    default: 'DBT Contracts results'
  path:
    description: |-
      Path to a JSON file which contains the results of a dbt-contracts execution as a list of annotations.
    default: 'contracts_results.json'
  additional-file-dir:
    description: |-
      When working with a nested dbt project,
      appending this additional parent file dir to the paths in the results.
  ignore-missing-file:
    description: Ignore if the file which contains annotations is missing
    required: false
    default: 'true'
  token:
    description: |-
      Token used to interact with the GitHub API.
      Currently only used to get the url of the summary table.
      This token must have the permissions 'contents: read' and 'actions: read' to get the jobs from the API.
      If not provided, a link to the summary table will not be generated.
    required: false
    default: ${{ github.token }}
  job-name:
    description: |-
      The github job name. Currently only used to get the url of the summary table.
      If not provided, a link to the summary table will not be generated.
    required: false
    default: ${{ github.job }}
  event-number:
    description: |-
      The github event number i.e. the pull request number. 
      Currently only used to get the url of the summary table when the action is being run as part of a PR.
    required: false
    default: ${{ github.event.number }}
runs:
  using: "composite"
  steps:
    - name: Check file exists
      if: ${{ ! inputs.ignore-missing-file }}
      shell: bash
      env:
        ANNOTATIONS_PATH: ${{ inputs.path }}
      run: |
        if [ ! -f "$ANNOTATIONS_PATH" ]; then
            echo "File not found: $ANNOTATIONS_PATH"
            exit 1
        fi

    - name: Populate summary
      shell: bash
      env:
        ANNOTATIONS_PATH: ${{ inputs.path }}
        TITLE: ${{ inputs.title }}
        FILE_DIR: ${{ inputs.additional-file-dir }}
      run: ${{ github.action_path }}/dist/summarise_results.sh

    - name: Show summary url
      shell: bash
      if: ${{ inputs.token != '' || inputs.job-name != '' }}
      env:
        GH_TOKEN: ${{ inputs.token }}
        GH_JOB_NAME: ${{ inputs.job-name }}
        GH_EVENT_NUMBER: ${{ inputs.event-number }}
      run: ${{ github.action_path }}/dist/show_summary_url.sh
