name: 'Summarise dbt-contracts results'
branding:
  icon: 'table'
  color: 'purple'
author: 'George Martin Marino'
description: 'Creates a summary table on actions to summarise results from dbt-contracts'
inputs:
  title:
    description: 'Title of the summary'
    required: false
    default: 'DBT Contracts results'
  path:
    description: |-
      Path to a JSON file which contains the results of a dbt-contracts execution as a list of annotations.
    default: 'contracts_results.json'
  additional-file-dir:
    description: |-
      When working with a nested dbt project,
      appending this additional parent file dir to the paths in the results.
#  repo-token:
#    description: Token used to interact with the GitHub API.
#    required: true
  ignore-missing-file:
    description: Ignore if the file which contains annotations is missing
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Check file exists
      if: ${{ ! inputs.ignore-missing-file }}
      shell: bash
      env:
        ANNOTATIONS_PATH: ${{ inputs.path }}
      run: |
        if [ ! -f "$ANNOTATIONS_PATH" ]; then
            echo "File not found: $ANNOTATIONS_PATH"
            exit 1
        fi

    - name: Set GitHub Path
      shell: bash
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Populate summary
      shell: bash
      env:
        ANNOTATIONS_PATH: ${{ inputs.path }}
        TITLE: ${{ inputs.title }}
        FILE_DIR: ${{ inputs.additional-file-dir }}
      run: dist/summarise_results.sh

    - name: Show summary url
      shell: bash
      run: dist/show_summary_url.sh
